[alias]
test-upstream = "run --bin test-upstream"
coverage = "llvm-cov --workspace --all-targets --lcov --output-path coverage/lcov.info"
coverage-html = "llvm-cov --workspace --all-targets --html --output-dir coverage/html"
